-- 코드를 입력하세요
SELECT
    mp.MEMBER_ID,
    mp.MEMBER_NAME,
    mp.GENDER,
    DATE_FORMAT(mp.DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE mp
WHERE DATE_FORMAT(mp.DATE_OF_BIRTH, '%m') = '03'
AND mp.GENDER = 'W'
AND mp.TLNO IS NOT NULL
ORDER BY mp.MEMBER_ID ASC