-- 코드를 입력하세요
SELECT
    b.BOOK_ID,
    DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK b
WHERE DATE_FORMAT(b.PUBLISHED_DATE, '%Y') = '2021'
AND b.CATEGORY = '인문'
ORDER BY b.PUBLISHED_DATE